import React from 'react';

export function Intro(props) {
  return (
    <div className="intro">
      <h1>Mountain bike brake force visualisation</h1>
      <p>This tool takes brake pad and rotor material out of the equation and looks simply at the leverage ratio of different brakes. <strong>Hydraulic leverage</strong> is generated by the difference in surface area between the master cylinder in the lever and slave cylinders in the caliper. <strong>Mechanical leverage</strong> stems from the relation between a lever blade's length and its pivot point. <strong>Total leverage</strong> is the product of these two.</p>
      <h5>Disclaimer</h5>
      <p class="small">The data is in no way complete, and the mechanical leverage data has some caveats. There is no leverage curve calculated, so data are an estimated average, which may deviate from reality. Also, the mechanical leverage at the brake's contact point depends on the lever throw and vice versa, which is not taken into account. There is no lever throw data, which means that a mix & match brake might be theoretically powerful, but also unusable, with a lever throw well beyond the bars.</p>
    </div>
  )
}

export function Copyright(props) {
  return (
    <div className="copyright">
      <h4>Copyrights</h4>
      <p>Brake data collected by <a href="https://ridemonkey.bikemag.com/threads/frankenbrakes-and-brake-improvement-discussion.274164/" target="_blank" rel="noopener noreferrer">Udi on RideMonkey</a></p>
      <p>Visualisation tool created by <a href="https://ddzyne.nl" target="_blank" rel="noopener noreferrer">Ddzyne</a></p>
    </div>
  )
}
